=== 104306051/test/ROCIncomeTaxReturn.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- ELEMENT -->

<!ELEMENT incomeTaxReturnSample (header, form, footer)>

<!ELEMENT header (notice, type, head, headInstructions, headerForm)>
<!ELEMENT headerForm (head, format, office, serviceArea, boxNumber, pageNumber)>

<!ELEMENT form (notice*, taxPayerAndTaxAllowance, comprehensiveIncomeTotal, deductions, taxCalculationFormula, useSavingsAccountTaxRefund, creditCardTax)>
<!ELEMENT taxPayerAndTaxAllowance (name, supportingRelatives, reduceTax+, taxAllowanceTotal_DM)>
<!ELEMENT name (taxPayer_DD, spouse_SS, householdRegistrationWhenDeclaring, notificationSendingPlace, contactPhoneNumber)>
<!ELEMENT taxPayer_DD (name, iDNumber, birthYear, disabilities)>
<!ELEMENT spouse_SS (name, iDNumber, birthYear, disabilities)>
<!ELEMENT householdRegistrationWhenDeclaring (rent, city, district, village, neighborhood, road, section, lane, alley, number, floor, room)>
<!ELEMENT notificationSendingPlace (rent, city, district, village, neighborhood, road, section, lane, alley, number, floor, room)>
<!ELEMENT contactPhoneNumber (phoneNumber1, phoneNumber2)>
<!ELEMENT supportingRelatives (loginCode*)>
<!ELEMENT loginCode (name, iDNumber, head, birthYear, cohabitation, learning, disabilities)>
<!ELEMENT reduceTax (type, people, total, reviewNumberOfPeople)>
<!ELEMENT comprehensiveIncomeTotal (income*, totalIncome_YM, spousetotalIncome_YN, comprehensiveIncomeTotal_AA, totalWithholdingTaxAndDeductibleTaxAmount_AG)>
<!ELEMENT income (people*)>
<!ELEMENT people (name, total, withholdingTaxOrDeductibleTaxAmount)>
<!ELEMENT deductions (deductionsItem*, totalDeductions, comprehensiveNetIncomeCalculation)>
<!ELEMENT deductionsItem (instructions, people*, subtotal, authorityAudit)>
<!ELEMENT totalDeductions (subtotal, authorityAudit)>
<!ELEMENT comprehensiveNetIncomeCalculation (calculationFormula)>
<!ELEMENT calculationFormula (comprehensiveIncome, allAllowances, allDeductions, comprehensiveNetIncome)>
<!ELEMENT taxCalculationFormula (type*)>
<!ELEMENT type (calculationFormula*, authorityAudit, notice)>
<!ELEMENT calculationFormula (comprehensiveNetIncome | taxRate | progressiveDifference | payable | allwithholdingTaxAndTaxDeductible | refundOfTax | shouldPayTheirOwnTaxes | salaryTaxSeparatedBySalaryIncome | taxationForTaxPayers | payrollIncomeDeductionsForPayrollTaxation | netSalaryOfPayrollTaxation | taxPayableSeparatelyFromTheTaxablePortion | excludingNetIncomeFromTheSeparateTaxPortionOfPayroll | excludingTaxPayableForTheSeparateTaxPortionOfPayroll | taxesForVariousTypesOfIncome | taxationAllowancesForSeparateTaxationOfVariousTypesOfincome | taxDeductionsForSalaryIncomeForSeparateTaxationOfVariousTypesOfIncome | separateDeductionsForSavingsAndInvestmentsOfTaxCollectorsOfVariousTypesOfIncome | specialDeductionsForPhysicalAndMentalDisabilitiesForIndividualIncomeTaxes | netIncomeOfVariousTypesOfIncomeSeparatelyTaxed | taxPayableForSeparateTaxationOfVariousTypesOfIncome | reduceTax | excludingNetIncomeFromSeparateTaxationOfVariousTypesOfIncome | excludingTaxPayableForSeparateTaxationOfVariousTypesOfIncome)*>
<!ELEMENT useSavingsAccountTaxRefund (notice*, name, iDNumber, financialInstitutions, assessingAgencyDesignation, account, postOffice)>
<!ELEMENT financialInstitutions (generalAgency, branches)>
<!ELEMENT account (separate, subject, accountNumber, inspectionNumber)>
<!ELEMENT postOffice (officeName, depositReserve, transferFundsAccount)>
<!ELEMENT depositReserve (bureauNumber, depositBookDepositAccount)>
<!ELEMENT creditCardTax (notice, bV, authorizationNumber, cardholder)>
<!ELEMENT authorizationNumber (number*)>
<!ELEMENT cardholder (taxpayer_DD, spouse_SS)>

<!ELEMENT footer (section1, section2)>
<!ELEMENT section1 (taxpayerSignOrStamp, notice+, attachmentArea, receivingAgencyReceiptStampAndDate)>
<!ELEMENT attachmentArea (noAttachment, attachment)>
<!ELEMENT attachment (notice*)>
<!ELEMENT section2 (received, notice*, attachmentArea, receivingAgencyReceiptStampAndDate)>
<!ELEMENT received (name, gender, city, district, village, neighborhood, road, section, lane, alley, number, floor, room)>
<!ELEMENT attachmentArea (notice, noAttachment, attachment)>

<!-- PCDATA with ELEMENT -->

<!ELEMENT notice (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT head (#PCDATA)>
<!ELEMENT headInstructions (#PCDATA)>
<!ELEMENT format (#PCDATA)>
<!ELEMENT office (#PCDATA)>
<!ELEMENT serviceArea (#PCDATA)>
<!ELEMENT boxNumber (#PCDATA)>
<!ELEMENT pageNumber (#PCDATA)>
<!ATTLIST notice check (true | false) "false">
<!ELEMENT name (#PCDATA)>
<!ELEMENT iDNumber (#PCDATA)>
<!ELEMENT birthYear (#PCDATA)>
<!ATTLIST birthdisabilities check (true | false) "false">
<!ATTLIST rent check (true | false) "false">
<!ELEMENT city (#PCDATA)>
<!ELEMENT district (#PCDATA)>
<!ELEMENT village (#PCDATA)>
<!ELEMENT neighborhood (#PCDATA)>
<!ELEMENT road (#PCDATA)>
<!ELEMENT section (#PCDATA)>
<!ELEMENT lane (#PCDATA)>
<!ELEMENT alley (#PCDATA)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT floor (#PCDATA)>
<!ELEMENT room (#PCDATA)>
<!ATTLIST notificationSendingPlace status (同上 | none) "同上">
<!ELEMENT phoneNumber1 (#PCDATA)>
<!ELEMENT phoneNumber2 (#PCDATA)>
<!ATTLIST loginCode code (D01 | D02 | D03 | D04 | D05 | D06) #REQUIRED>
<!ATTLIST cohabitation status (是 | 否) "是">
<!ATTLIST learning status (是 | 否) "是">
<!ATTLIST disabilities check (true | false) "false">
<!ELEMENT people (#PCDATA)>
<!ELEMENT total (#PCDATA)>
<!ELEMENT reviewNumberOfPeople (#PCDATA)>
<!ELEMENT taxAllowanceTotal_DM (#PCDATA)>
<!ATTLIST income type (Salary income | Interest income | Profit income | Welfare | Contribution fees below 180,000) #REQUIRED>
<!ELEMENT withholdingTaxOrDeductibleTaxAmount (#PCDATA)>
<!ELEMENT WithholdingTax (#PCDATA)>
<!ELEMENT totalIncome_YM (#PCDATA)>
<!ELEMENT spousetotalIncome_YN (#PCDATA)>
<!ELEMENT comprehensiveIncomeTotal_AA (#PCDATA)>
<!ELEMENT totalWithholdingTaxAndDeductibleTaxAmount_AG (#PCDATA)>
<!ATTLIST deductionsItem type (Special deductions for salary income | Savings Special Deductions | Standard Deduction | Disabilities Special Deduction | Education Tuition Special Deduction | Preschoolers Special Deduction) #REQUIRED>
<!ELEMENT instructions (#PCDATA)>
<!ATTLIST people type (Taxpayer | Spouse | All dependents) #REQUIRED>
<!ELEMENT totalSalaryIncomeForTheWholeYear (#PCDATA)>
<!ELEMENT deductible (#PCDATA)>
<!ELEMENT subtotal (#PCDATA)>
<!ELEMENT authorityAudit (#PCDATA)>
<!ATTLIST instructions check (true | false) #REQUIRED>
<!ATTLIST instructions people (0 | 1 | 2 | 3 | 4 | 5) "0">
<!ATTLIST comprehensiveIncome operation (+ | - | * | / | none) "+">
<!ATTLIST allAllowances operation (+ | - | * | / | none) "-">
<!ATTLIST allDeductions operation (+ | - | * | / | none) "-">
<!ATTLIST comprehensiveNetIncome operation (+ | - | * | / | none) "none">
<!ATTLIST comprehensiveIncome sign CDATA #FIXED "AA">
<!ATTLIST allAllowances sign CDATA #FIXED "DM">
<!ATTLIST allDeductions sign CDATA #FIXED "AB1">
<!ATTLIST comprehensiveNetIncome sign CDATA #FIXED "AE">
<!ATTLIST type name (Combined calculation tax amount | Separately calculated tax amount for salary income | Taxes are calculated separately for various types of income) #REQUIRED>
<!ATTLIST type number (1 | 2 | 3) #REQUIRED>

<!ATTLIST comprehensiveNetIncome operation (+ | - | * | / | none) #REQUIRED>
<!ATTLIST taxRate operation (+ | - | * | / | none) #REQUIRED>
<!ATTLIST progressiveDifference operation (+ | - | * | / | none) #REQUIRED>
<!ATTLIST payable operation (+ | - | * | / | none) #REQUIRED>
<!ATTLIST allwithholdingTaxAndTaxDeductible operation (+ | - | * | / | none) #REQUIRED>
<!ATTLIST refundOfTax operation (+ | - | * | / | none) #REQUIRED>
<!ATTLIST shouldPayTheirOwnTaxes operation (+ | - | * | / | none) #REQUIRED>
<!ATTLIST salaryTaxSeparatedBySalaryIncome operation (+ | - | * | / | none) #REQUIRED>
<!ATTLIST taxationForTaxPayers operation (+ | - | * | / | none) #REQUIRED>
<!ATTLIST payrollIncomeDeductionsForPayrollTaxation operation (+ | - | * | / | none) #REQUIRED>
<!ATTLIST netSalaryOfPayrollTaxation operation (+ | - | * | / | none) #REQUIRED>
<!ATTLIST taxPayableSeparatelyFromTheTaxablePortion operation (+ | - | * | / | none) #REQUIRED>
<!ATTLIST excludingNetIncomeFromTheSeparateTaxPortionOfPayroll operation (+ | - | * | / | none) #REQUIRED>
<!ATTLIST excludingTaxPayableForTheSeparateTaxPortionOfPayroll operation (+ | - | * | / | none) #REQUIRED>
<!ATTLIST taxesForVariousTypesOfIncome operation (+ | - | * | / | none) #REQUIRED>
<!ATTLIST taxationAllowancesForSeparateTaxationOfVariousTypesOfincome operation (+ | - | * | / | none) #REQUIRED>
<!ATTLIST taxDeductionsForSalaryIncomeForSeparateTaxationOfVariousTypesOfIncome operation (+ | - | * | / | none) #REQUIRED>
<!ATTLIST separateDeductionsForSavingsAndInvestmentsOfTaxCollectorsOfVariousTypesOfIncome operation (+ | - | * | / | none) #REQUIRED>
<!ATTLIST specialDeductionsForPhysicalAndMentalDisabilitiesForIndividualIncomeTaxes operation (+ | - | * | / | none) #REQUIRED>
<!ATTLIST netIncomeOfVariousTypesOfIncomeSeparatelyTaxed operation (+ | - | * | / | none) #REQUIRED>
<!ATTLIST taxPayableForSeparateTaxationOfVariousTypesOfIncome operation (+ | - | * | / | none) #REQUIRED>
<!ATTLIST reduceTax operation (+ | - | * | / | none) #REQUIRED>
<!ATTLIST excludingNetIncomeFromSeparateTaxationOfVariousTypesOfIncome operation (+ | - | * | / | none) #REQUIRED>

<!ATTLIST payable sign CDATA #FIXED "AF">
<!ATTLIST allwithholdingTaxAndTaxDeductible sign CDATA #FIXED "AG">
<!ATTLIST refundOfTax sign CDATA #FIXED "AI">
<!ATTLIST shouldPayTheirOwnTaxes sign CDATA #FIXED "AH">
<!ATTLIST salaryTaxSeparatedBySalaryIncome sign CDATA #FIXED "AD">
<!ATTLIST taxesForVariousTypesOfIncome sign CDATA #FIXED "YT">

<!ATTLIST reduceTax name (Excluding tax allowances for separate taxation of various types of income | Excluding deductions for individual tax collectors of various types of income) #REQUIRED>

<!ELEMENT generalAgency (#PCDATA)>
<!ELEMENT branches (#PCDATA)>
<!ELEMENT assessingAgencyDesignation (#PCDATA)>
<!ELEMENT separate (#PCDATA)>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT accountNumber (#PCDATA)>
<!ELEMENT inspectionNumber (#PCDATA)>
<!ELEMENT officeName (#PCDATA)>
<!ELEMENT depositReserve (#PCDATA)>
<!ELEMENT bureauNumber (#PCDATA)>
<!ELEMENT depositBookDepositAccount (#PCDATA)>
<!ELEMENT transferFundsAccount (#PCDATA)>
<!ELEMENT bV (#PCDATA)>
<!ATTLIST taxpayer_DD check (true | false) "false">
<!ATTLIST spouse_SS check (true | false) "false">
<!ELEMENT taxpayerSignOrStamp (#PCDATA)>
<!ATTLIST noAttachment check (true | false) "true">
<!ATTLIST attachment check (true | false) "true">
<!ELEMENT receivingAgencyReceiptStampAndDate (#PCDATA)>

=== 104306051/test/105IncomeTaxReturnSample1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE incomeTaxReturnSample SYSTEM "ROCIncomeTaxReturn.dtd"[
   
	<!ENTITY type "簡式">
    <!ENTITY head1 "中華民國105年度綜合所得稅結算申報書">
    <!ENTITY head2 "(本欄納稅義務人不必填寫)">
    <!ENTITY headInstructions "(自105年1月1日至12月31日取得的所得都要申報) 單位：新臺幣元">
    
	<!ENTITY top_n1 "附件裝訂處請依序裝訂於申報書錢且勿黏貼：1.繳稅取款委託書、自動櫃員機轉帳繳納交易明細表。2.自繳稅款繳款書證明聯。3.其他證明文件(屬國外文件應自行節譯註記)。">
    <!ENTITY n2 "夫妻分居，屬符合民法第1010條第2項難於維持共同生活，部同居已達6個月以上，向法院聲請宣告採用分別財產制、同法第1089條之1不繼續共同生活達6個月以上，經法院裁定未成年子女權利義務之行使或負擔，或屬依家庭暴力防治法規定取得通常保護令，得各自辦理結算申報及計算稅額者，請打勾，並請檢附相關文件(BF)。(請看說明二之一)">
    <!ENTITY n3 "不符合上開規定，而無法合併申報之分居夫妻(不包含因工作因素分隔兩地或戶籍地不同等情形)，請打勾，並於申報書上填寫配偶姓名及身分證統一編號(BD)。如需分別開單計稅者，請另附申請書。">
    <!ENTITY n4 "納稅義務人為大陸地區人民，105年度在臺居、停留合計滿183天者，請打勾。【申報注意事項詳背面說明十五】">
    <!ENTITY n5 "單身者，請填寫第1欄計算式；有配偶者，可就下列稅額計算式選用較有利者。請於選用欄項打勾：">
    <!ENTITY n6 "單身者或夫妻所得採合併計算稅額者，請填寫第1欄計算式。">
    <!ENTITY n7 "夫妻選擇納稅義務人或配偶之薪資所得分開計算稅額者，請填寫第2欄計算式。">
    <!ENTITY n8 "夫妻選擇納稅義務人或配偶之各類所得分開計算稅額者，請填寫第3欄計算式。">
    <!ENTITY n9 "※應納稅額請計算至元為止，不足元者無條件捨去。">
    <!ENTITY n10 "本欄帳號資料限供直撥退稅使用，如欲提供存款帳戶辦理繳稅，請另填寫繳稅取款委託書（詳說明十四之(二)2）">
    <!ENTITY n11 "限本申報書之納稅義務人、配偶或申報扶養親屬帳戶">
    <!ENTITY n12 "退稅款不利用直撥退稅轉入存款帳戶或退稅款無法轉入存款帳戶者，國稅局會直接寄送退稅憑單（支票）或退稅通知，納稅義務人不必至自動提款機前操作或輸入任何資料。">
    <!ENTITY n13 "經國稅局核定退稅金額30元以下且不利用直撥退稅轉入存款帳戶或退稅款無法轉入存款帳戶者，同意不領取該筆退稅款（BY）。">
    <!ENTITY n14 "限申報書內納稅義務人、配偶名義持有之信用卡">
    <!ENTITY n15 "※1.如郵寄申報時，請於信封左下角註明「綜合所得申報書」，並掛號逕寄戶籍所在地之國稅局所屬分局、稽徵所或服務處。">
    <!ENTITY n16 "2.逾期申報者，僅得送（寄）戶籍所在地國稅局。">
    <!ENTITY n17 "1.繳稅取款委託書、自動櫃員機轉帳繳納交易明細表">
    <!ENTITY n18 "2.自繳稅款繳款書證明聯">
    <!ENTITY n19 "3.其他證明文件(屬國外文件應自行節譯註記)">
    <!ENTITY n20 "※1.本聯請自行填寫。">
    <!ENTITY n21 "2.為保障權益，本收據請保存7年，以便日後查考。">
    <!ENTITY n22 "3.如郵寄申報，請撕下自存。">
    <!ENTITY n23 "105年度綜合所得稅結算申報表及">
    <!ENTITY n24 "(掛號郵寄申報，郵局收據黏貼處)">
    <!ENTITY n25 "財政部臺北國稅局 106.04. 5,500張廣告">
    
    <!ENTITY reduceTax1 "年滿70歲之納稅義務人、配偶及受扶養直系尊親屬，每人免稅額127,500元">
    <!ENTITY reduceTax2 "未滿70歲之納稅義務人、配偶及非屬上項之受扶養親屬，每人免稅額85,000元">
    
    <!ENTITY specialInstructions1 "有薪資所得者，每人可扣除128,000元，但其全年薪資所得總額未達128,000元者，僅得就其全年薪資所得總額全數扣除。">
    <!ENTITY specialInstructions2 "有利息所得者，納稅義務人、配偶及受扶養親屬，全年合計不超過27萬元者，得全數扣除；超過27萬元者，以扣除27萬元為限。選擇各類所得分開計稅者，如全戶利息所得超過27萬元，由分開計稅者之他方及受扶養親屬就其利息所得在27萬元限額內先予減除，減除後如有剩餘，再由分開計稅者減除；如全戶利息所得在27萬元以下，則各自就其利息所得部分減除。">
    <!ENTITY specialInstructions3 "(1)單身者90,000元。(採用列舉扣除者，請使用一般申請書申報)">
    <!ENTITY specialInstructions4 "(2)夫妻合併申報者180,000元。">
    <!ENTITY specialInstructions5 "納稅義務人、配偶或受扶養親屬為領有身心障礙手冊者或精神疾病嚴重病人，每人可扣除128,000元。">
    <!ENTITY specialInstructions6 "納稅義務人申報扶養之子女就讀大專以上院校之教育學費，每人最多扣除25,000元，已接受政府補助者，應以扣除該補助之餘額列報。但就讀空大、空專及五專前3年不適用本項扣除額。">
    <!ENTITY specialInstructions7 "納稅義務人申報扶養5歲以下之子女，每人每年可扣除25,000元，但經減除本特別扣除額後，全年綜合所得稅適用稅率或採本人或配偶之薪資所得或各類所得分開計算稅額適用稅率在20以上或基本所得額超過67萬元者，不適用本項扣除。">
    
]>
<incomeTaxReturnSample>
    <header>
        <notice>&top_n1;</notice> 
        <type>&type;</type>
        <head>&head1;</head>
        <headInstructions>&headInstructions;</headInstructions>
        <headerForm>
            <head>&head2;</head>
            <format>11</format>
            <office></office>
            <serviceArea></serviceArea>
            <boxNumber></boxNumber>
            <pageNumber></pageNumber>
        </headerForm>
    </header>
    <form>
        <notice check = 'false'>&n2;</notice>
        <notice check = 'false'>&n3;</notice>
        <notice check = 'false'>&n4;</notice>
        <taxPayerAndTaxAllowance>
            <name>
                <taxPayer_DD>
                    <name>張志明</name>
                    <iDNumber>A100266713</iDNumber>
                    <birthYear>60</birthYear>
                    <disabilities check = 'false'/>
                </taxPayer_DD>

                <spouse_SS>
                    <name>陳春嬌</name>
                    <iDNumber>F201322482</iDNumber>
                    <birthYear>63</birthYear>
                    <disabilities check = 'false'/>
                </spouse_SS>

                <householdRegistrationWhenDeclaring>
                    <rent check = '否' />
                    <city>臺北市</city>
                    <district>大安區</district>
                    <village>龍安里</village>
                    <neighborhood>2</neighborhood>
                    <road>新生南路</road>
                    <section>2</section>
                    <lane></lane>
                    <alley></alley>
                    <number>80</number>
                    <floor>4</floor>
                    <room></room>                    
                </householdRegistrationWhenDeclaring>
                
                <notificationSendingPlace status = '同上'>
                    <city></city>
                    <district></district>
                    <village></village>
                    <neighborhood></neighborhood>
                    <road></road>
                    <section></section>
                    <lane></lane>
                    <alley></alley>
                    <number></number>
                    <floor></floor>
                    <room></room>  
                </notificationSendingPlace>

                <contactPhoneNumber>
                    <phoneNumber1>(02)2311-3711</phoneNumber1>
                    <phoneNumber2>(02)2311-3899</phoneNumber2>
                </contactPhoneNumber>
            </name>
            <supportingRelatives>
                <loginCode code = 'D01'>
                    <name>張無忌</name>
                    <iDNumber>A103849043</iDNumber>
                    <head>子</head>
                    <birthYear>94</birthYear>
                    <cohabitation status = '是' />
                    <learning status = '是' />
                    <disabilities check = 'false' />
                </loginCode>
                <loginCode code = 'D02'>
                    <name>王志玲</name>
                    <iDNumber>A200831641</iDNumber>
                    <head>母</head>
                    <birthYear>30</birthYear>
                    <cohabitation status = '是' />
                    <learning status = '否' />
                    <disabilities check = 'false' />
                </loginCode>
                <loginCode code = 'D03'>
                    <name></name>
                    <iDNumber></iDNumber>
                    <head></head>
                    <birthYear></birthYear>
                    <cohabitation status = '否' />
                    <learning status = '否' />
                    <disabilities check = 'false' />
                </loginCode>
            </supportingRelatives>

            <reduceTax>
                <type>&reduceTax1;</type>
                <people>1</people>
                <total>127,500</total>
                <reviewNumberOfPeople></reviewNumberOfPeople>
            </reduceTax>
            <reduceTax>
                <type>&reduceTax2;</type>
                <people>3</people>
                <total>255,000</total>
                <reviewNumberOfPeople></reviewNumberOfPeople>
            </reduceTax>
            <taxAllowanceTotal_DM>382,500</taxAllowanceTotal_DM>

        </taxPayerAndTaxAllowance>

        <comprehensiveIncomeTotal>
            <income type = 'Salary income'>
                <people>
                    <name>張志明</name>
                    <total>867,000</total>
                    <withholdingTaxOrDeductibleTaxAmount>33,300</withholdingTaxOrDeductibleTaxAmount>
                </people>

                <people>
                    <name>陳春嬌</name>
                    <total>616,000</total>
                    <withholdingTaxOrDeductibleTaxAmount>19,400</withholdingTaxOrDeductibleTaxAmount>
                </people>

                <people>
                    <name>張無忌</name>
                    <total>40,000</total>
                    <withholdingTaxOrDeductibleTaxAmount>2,400</withholdingTaxOrDeductibleTaxAmount>
                </people>
            </income>

            <income type = 'Interest income'>
                <people>
                    <name>張志明</name>
                    <total>24,000</total>
                    <withholdingTaxOrDeductibleTaxAmount>2,400</withholdingTaxOrDeductibleTaxAmount>
                </people>

                <people>
                    <name>王志玲</name>
                    <total>70,000</total>
                    <withholdingTaxOrDeductibleTaxAmount>7,000</withholdingTaxOrDeductibleTaxAmount>
                </people>

                <people>
                    <name></name>
                    <total></total>
                    <withholdingTaxOrDeductibleTaxAmount></withholdingTaxOrDeductibleTaxAmount>
                </people>
            </income>

            <income type = 'Profit income'>
                <people>
                    <name>陳春嬌</name>
                    <total>137,800</total>
                    <withholdingTaxOrDeductibleTaxAmount>10,000</withholdingTaxOrDeductibleTaxAmount>
                </people>

                <people>
                    <name></name>
                    <total></total>
                    <withholdingTaxOrDeductibleTaxAmount></withholdingTaxOrDeductibleTaxAmount>
                </people>

                <people>
                    <name></name>
                    <total></total>
                    <withholdingTaxOrDeductibleTaxAmount></withholdingTaxOrDeductibleTaxAmount>
                </people>

                <people>
                    <name></name>
                    <total></total>
                    <withholdingTaxOrDeductibleTaxAmount></withholdingTaxOrDeductibleTaxAmount>
                </people>

                <people>
                    <name></name>
                    <total></total>
                    <withholdingTaxOrDeductibleTaxAmount></withholdingTaxOrDeductibleTaxAmount>
                </people>
            </income>

            <income type = 'Welfare'>
                <people>
                    <name>張志明</name>
                    <total>5,000</total>
